### PR TITLE
fix: decoding zip entry filenames with Windows-1252

### PR DESCRIPTION
**Pull request by Gustash**
## Why

Some games like `Plants vs. Zombies™ Game of the Year Edition` have filenames with non-UTF-8 characters.

As an example, here are the bytes of entry which is not a valid UTF-8 encoded string:

```
[83, 117, 112, 112, 111, 114, 116, 47, 69, 65, 32, 72, 101, 108, 112, 47, 65, 115, 105, 115, 116, 101, 110, 99, 105, 97, 32, 84, 130, 99, 110, 105, 99, 97, 46, 114, 116, 102]
```

It is, however, a valid Windows-1252 encoded string. Unzipping the downloaded zip manually in the OS gives me the same filenames as those obtained from decoding as Windows-1252. Furthermore, the default encoding for filenames in Windows, when you zip a file, is Windows-1252.

All this seems to suggest that the correct encoding is Windows-1252. It is also compatible with UTF-8 characters, so this should not be an issue should some zips encode the filenames as UTF-8 only.

### CODE REVIEW

**Comment by derrod** [comment]
Per the ZIP file standard: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

> D.1 The ZIP format has historically supported only the original IBM PC character 
encoding set, commonly referred to as IBM Code Page 437.  This limits storing 
file name characters to only those within the original MS-DOS range of values 
and does not properly support file names in other character encodings, or 
languages. To address this limitation, this specification will support the 
following change. 

> D.2 If general purpose bit 11 is unset, the file name and comment SHOULD conform 
to the original ZIP character encoding.  If general purpose bit 11 is set, the 
filename and comment MUST support The Unicode Standard, Version 4.1.0 or 
greater using the character encoding form defined by the UTF-8 storage 
specification.  The Unicode Standard is published by the The Unicode
Consortium (www.unicode.org).  UTF-8 encoded data stored within ZIP files 
is expected to not include a byte order mark (BOM).

**Comment by Gustash** [comment]
> Per the ZIP file standard: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
> 
> > D.1 The ZIP format has historically supported only the original IBM PC character
> > encoding set, commonly referred to as IBM Code Page 437.  This limits storing
> > file name characters to only those within the original MS-DOS range of values
> > and does not properly support file names in other character encodings, or
> > languages. To address this limitation, this specification will support the
> > following change.
> 
> > D.2 If general purpose bit 11 is unset, the file name and comment SHOULD conform
> > to the original ZIP character encoding.  If general purpose bit 11 is set, the
> > filename and comment MUST support The Unicode Standard, Version 4.1.0 or
> > greater using the character encoding form defined by the UTF-8 storage
> > specification.  The Unicode Standard is published by the The Unicode
> > Consortium ([www.unicode.org](http://www.unicode.org)).  UTF-8 encoded data stored within ZIP files
> > is expected to not include a byte order mark (BOM).

Bit 11 seems to always be not set. So this specification does not apply to this specific problem

**Comment by derrod** [comment]
It's providing additional context as to why decoding the names as utf-8 is leading to wrong results, as the default encoding is IBM 437 which Windows 1252 is largely (if not fully) compatible with.

**Comment by Gustash** [comment]
> It's providing additional context as to why decoding the names as utf-8 is leading to wrong results, as the default encoding is IBM 437 which Windows 1252 is largely (if not fully) compatible with.

Ah yes, thank you for the clarification. From what I could find online, Windows generally encodes with IBM-850, but depending on the system language may use Windows-1252 when encoding a filename. Windows-1252 seems like the best general guess for the encoding on zips created in Windows.

**Review by battledash — APPROVED** [review]

**Pull request merged**
